<?xml version='1.1' encoding='UTF-8'?>
<Tag plugin="workflow-support@839.v35e2736cfd5c">
  <node class="cps.n.StepEndNode" plugin="workflow-cps@3659.v582dc37621d8">
    <parentIds>
      <string>20</string>
    </parentIds>
    <id>21</id>
    <startId>18</startId>
  </node>
  <actions>
    <wf.a.TimingAction plugin="workflow-api@1208.v0cc7c6e0da_9e">
      <startTime>1684351805959</startTime>
    </wf.a.TimingAction>
    <wf.a.ErrorAction plugin="workflow-api@1208.v0cc7c6e0da_9e">
      <error class="org.jenkinsci.plugins.workflow.steps.SynchronousResumeNotSupportedException" plugin="workflow-step-api@639.v6eca_cd8c04a_a_">
        <detailMessage>Resume after a restart not supported for non-blocking synchronous steps</detailMessage>
        <stackTrace>
          <trace>org.jenkinsci.plugins.workflow.steps.SynchronousNonBlockingStepExecution.onResume(SynchronousNonBlockingStepExecution.java:75)</trace>
          <trace>org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ParallelResumer.lambda$run$5(FlowExecutionList.java:378)</trace>
          <trace>jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)</trace>
          <trace>jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:68)</trace>
          <trace>jenkins.util.ErrorLoggingExecutorService.lambda$wrap$0(ErrorLoggingExecutorService.java:51)</trace>
          <trace>java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)</trace>
          <trace>java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)</trace>
          <trace>java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)</trace>
          <trace>java.base/java.lang.Thread.run(Thread.java:829)</trace>
        </stackTrace>
        <suppressedExceptions class="empty-list"/>
      </error>
    </wf.a.ErrorAction>
  </actions>
</Tag>